//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GameFrame.rc
//
#define IDCANCEL2                       4
#define IDR_COMMAND                     166
#define IDC_CHAT_MESSAGE                1004
#define IDC_USER_LIST_CONTROL           1030
#define IDC_BT_SEND_CHAT                1046
#define IDC_CHAT_EDIT                   1055
#define IDC_BT_CHAT_BUTTON_1            1060
#define IDC_BT_CHAT_BUTTON_2            1062
#define IDC_BT_CHAT_BUTTON_3            1064
#define IDC_BT_CHAT_BUTTON_4            1066
#define IDC_BT_CHAT_SHORT               1082
#define IDB_FRAME_MR                    1083
#define IDB_FRAME_TL                    1084
#define IDB_FRAME_TM                    1085
#define IDC_ALLOW_BACK_SOUND            2001
#define IDC_IN_COUNT                    2002
#define IDC_ZJG_MONEY                   2002
#define IDC_EDIT2                       2003
#define IDC_ZJG_PASSWORD                2003
#define IDB_FRAME_BL                    2004
#define IDB_FRAME_BM                    2005
#define IDC_STATIC_PASS                 2005
#define IDB_FRAME_BR                    2006
#define IDB_FRAME_ML                    2007
#define IDC_USER_PASSWORD               2009
#define IDC_STATIC_INFO                 2009
#define IDC_CHECK_ALL                   2010
#define IDB_FRAME_TR                    2011
#define IDC_BUTTON1                     2011
#define IDC_REGAIN_BUTTON               2011
#define IDB_BT_CLOSE                    2012
#define IDC_CHAT_MESSAGE2               2012
#define IDB_BT_MAX                      2013
#define IDB_BT_MIN                      2014
#define IDB_BT_RESORE                   2015
#define IDB_USER_LIST_TL                2018
#define IDB_USER_LIST_BL                2020
#define IDB_USER_LIST_BM                2021
#define IDB_USER_LIST_BR                2022
#define IDB_BT_CHAT_BUTTON_1            2023
#define IDB_USER_LIST_TM                2024
#define IDB_USER_LIST_TR                2025
#define IDB_USER_LIST_ML                2026
#define IDB_USER_LIST_MR                2027
#define IDB_BT_CHAT_BUTTON_2            2028
#define IDB_BT_CHAT_BUTTON_3            2029
#define IDB_BT_CHAT_BUTTON_4            2030
#define IDB_BT_CHAT_SHORT               2031
#define IDB_BT_SEND_CHAT                2032
#define IDB_CHAT_BL                     2033
#define IDB_CHAT_BM                     2034
#define IDB_CHAT_BR                     2035
#define IDB_CHAT_ML                     2036
#define IDB_CHAT_MR                     2037
#define IDB_CHAT_TL                     2038
#define IDB_CHAT_TM                     2039
#define IDB_CHAT_TR                     2040
#define IDB_USER_INFO_R                 2070
#define IDB_USER_INFO_L                 2071
#define IDB_USER_INFO_M                 2072
#define IDB_BT_CHAT_CLOSE               2073
#define IDB_BT_CHAT_CONTROL             2074
#define IDB_CHAT_CONTROL_BACK           2075
#define IDB_GAME_PROPERTY_L             2076
#define IDB_GAME_PROPERTY_M             2077
#define IDB_GAME_PROPERTY_R             2078
#define IDB_GAME_PROPERTY_ITEM          2081
#define IDB_BT_USER_INFO                2088
#define IDB_USER_MEDAL_R                2089
#define IDB_USER_MEDAL_L                2090
#define IDB_USER_MEDAL_M                2091
#define IDB_BT_RULE                     2095
#define IDB_BT_OPTION                   2097
#define IDB_BT_MUTE                     2098
#define IDB_OPTION_LOGO                 2100
#define IDD_GAME_OPTION                 2101
#define IDD_GENERAL_OPTION              2102
#define IDB_BT_SLIENT                   2103
#define IDD_DIALOG1                     2104
#define IDD_GAME_RULE                   2104
#define IDD_BANK_STORAGE                2105
#define IDD_DLG_MATCH_AWARDS            2106
#define IDB_BT_CLOSE_AWARDS             2107
#define IDD_ZJG_BAKER_STORAGE           2107
#define IDB_ZJG_ALL                     2108
#define IDB_ZJG_CLOSE                   2109
#define IDB_ZJG_LINK                    2110
#define IDB_ZJG_MAINBAKER               2111
#define IDB_BITMAP1                     2112
#define IDB_ZJG_MAKESURE                2112
#define IDD_ZJG_RECORD_PLAY             2114
#define IDB_BT_RECORD_CLOSE             2124
#define IDB_BT_RECORD_MIN               2125
#define IDB_BT_RECORD_OPEN              2126
#define IDB_BT_RECORD_PAUSE             2127
#define IDB_BT_REOCRD_PLAY              2128
#define IDB_BT_RECORD_PLAY              2128
#define IDB_BITMAP2                     2129
#define IDB_BITMAP3                     2130
#define IDB_BT_CLOSE_CHAT               2132
#define IDB_BT_OPEN_CHAT                2133
#define IDB_BITMAP4                     2134
#define IDB_BITMAP5                     2135
#define IDB_BITMAP6                     2136
#define IDB_BITMAP7                     2137
#define IDB_BITMAP8                     2138
#define IDB_BITMAP9                     2139
#define IDB_CONTROL_TL                  2140
#define IDB_CONTROL_TM                  2141
#define IDB_CONTROL_TR                  2142
#define IDB_CONTROL_BL                  2143
#define IDB_CONTROL_BM                  2144
#define IDB_CONTROL_BR                  2145
#define IDB_CONTROL_ML                  2146
#define IDB_CONTROL_MM                  2147
#define IDB_CONTROL_MR                  2148
#define IDB_PNG1                        2149
#define IDD_VOLUMN_SETTING              2150
#define IDB_VOLUMN_CANCEL               2151
#define IDB_VOLUMN_OK                   2152
#define IDB_VOLUMN_CLOSE                2153
#define IDB_BITMAP10                    2154
#define IDB_BT_CHAT_BUTTON              2154
#define IDB_PNG2                        2155
#define IDD_DIALOG2                     2156
#define IDD_TOPMSG_DIALOG               2156
#define IDD_GAME_CLOSE                  2158
#define IDB_PNG3                        2159
#define IDB_BT_CANCEL                   2162
#define IDB_BT_OK                       2163
#define IDB_PNG5                        2165
#define IDD_DIALOG3                     2166
#define IDD_MATCH_CONTROL               2166
#define IDD_DIALOG4                     2167
#define IDB_PNG4                        2169
#define IDB_PNG6                        2170
#define IDB_PNG7                        2172
#define IDB_PNG8                        2176
#define IDB_PNG9                        2177
#define IDD_GAME_GLAD_MESSAGE           2178
#define IDD_GAME_CONTROL                8011
#define IDB_GETGOLD                     8100
#define IDB_SAVEGOLD                    8101
#define IDB_CLOSE                       8102
#define IDB_BT_FRESH                    8103
#define IDC_ITEM_TAB                    9007
#define IDC_ALLOW_FRIEND_LOOKON         9010
#define IDC_ALLOW_SOUND                 9011
#define IDC_ALLOW_LOOKON                9012
#define IDC_NOTIFY_USER_INOUT           9013
#define IDC_FULL_GAME_VIEW              9014
#define IDC_DEFAULT                     9015
#define IDC_DEBAR_DETEST_CHAT           9015
#define IDM_KICK_USER                   32772
#define IDM_USER_LOGON                  32774
#define IDM_USER_LOCKED                 32777
#define IDM_SWITCH_ACCOUNTS             32778
#define IDM_COPY_USER_NICKNAME          32779
#define IDM_SEE_USER_LOCATION           32780
#define IDM_CREATE_ISER_WISPER          32781
#define IDM_SET_FRIEND_USER             32782
#define IDM_SET_COLLECTION              32783
#define IDM_ENTER_SERVER                32784
#define IDM_SET_DETEST_USER             32784
#define IDM_ENTER_TABLE                 32785
#define IDM_EXPAND_LIST                 32788
#define IDM_SHRINK_LIST                 32790
#define IDM_MESSAGE_HIDE_DETEST         32791
#define IDM_MESSAGE_SHOW_ALL            32792
#define IDM_MESSAGE_ONLY_FRIEND         32793
#define IDM_DELETE_SERVER_ITEM          32794
#define IDM_NULL_COMMAND                32794
#define IDM_CANCEL_CHAT_USER            32819
#define IDM_SET_CHAT_USER               32820
#define IDM_SEARCH_ONLINE_USER          32821
#define IDM_INVITE_USER                 32822
#define IDM_SHOW_USER_INFO              32826
#define IDM_SET_USER_NOTE               32827
#define IDM_USER_INFO_MANAGER           32830
#define IDM_LOOKON_USER                 32832
#define IDM_PLAY_GAME_TOGETHER          32834
#define IDM_SEND_BY_ENTER               32837
#define IDM_SEND_BY_CTRL_ENTER          32838
#define IDM_MORE_COLOR                  32840
#define IDM_SEARCH_TABLE                32844
#define IDM_ISSUE_MESSAGE               32858
#define IDM_MANAGER_SERVER              32859
#define IDM_MANAGER_ANDROID             32861
#define IDM_MANAGER_USER                32872
#define IDM_KILL_USER                   32874
#define IDM_TREASURE_PAY                32886
#define IDM_SERVICE_CENTER              32887
#define IDM_TREASURE_CENTER             32888

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2179
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2013
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
