// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameLogo.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GameLogo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace LogonServer {

void protobuf_ShutdownFile_GameLogo_2eproto() {
  delete PROTO_CESHI::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_GameLogo_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_GameLogo_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  PROTO_CESHI::default_instance_ = new PROTO_CESHI();
  PROTO_CESHI::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_GameLogo_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_GameLogo_2eproto_once_);
void protobuf_AddDesc_GameLogo_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_GameLogo_2eproto_once_,
                 &protobuf_AddDesc_GameLogo_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_GameLogo_2eproto {
  StaticDescriptorInitializer_GameLogo_2eproto() {
    protobuf_AddDesc_GameLogo_2eproto();
  }
} static_descriptor_initializer_GameLogo_2eproto_;
#endif

// ===================================================================

#ifndef _MSC_VER
const int PROTO_CESHI::kBUserIDFieldNumber;
const int PROTO_CESHI::kCbPlayStatusFieldNumber;
const int PROTO_CESHI::kCbMaxCallFieldNumber;
#endif  // !_MSC_VER

PROTO_CESHI::PROTO_CESHI()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:LogonServer.PROTO_CESHI)
}

void PROTO_CESHI::InitAsDefaultInstance() {
}

PROTO_CESHI::PROTO_CESHI(const PROTO_CESHI& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:LogonServer.PROTO_CESHI)
}

void PROTO_CESHI::SharedCtor() {
  _cached_size_ = 0;
  buserid_ = GOOGLE_LONGLONG(0);
  cbplaystatus_ = 0;
  cbmaxcall_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PROTO_CESHI::~PROTO_CESHI() {
  // @@protoc_insertion_point(destructor:LogonServer.PROTO_CESHI)
  SharedDtor();
}

void PROTO_CESHI::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void PROTO_CESHI::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const PROTO_CESHI& PROTO_CESHI::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_GameLogo_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_GameLogo_2eproto();
#endif
  return *default_instance_;
}

PROTO_CESHI* PROTO_CESHI::default_instance_ = NULL;

PROTO_CESHI* PROTO_CESHI::New() const {
  return new PROTO_CESHI;
}

void PROTO_CESHI::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<PROTO_CESHI*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(buserid_, cbmaxcall_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool PROTO_CESHI::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:LogonServer.PROTO_CESHI)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 bUserID = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &buserid_)));
          set_has_buserid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_cbPlayStatus;
        break;
      }

      // required int32 cbPlayStatus = 2;
      case 2: {
        if (tag == 16) {
         parse_cbPlayStatus:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cbplaystatus_)));
          set_has_cbplaystatus();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_cbMaxCall;
        break;
      }

      // required int32 cbMaxCall = 3;
      case 3: {
        if (tag == 24) {
         parse_cbMaxCall:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cbmaxcall_)));
          set_has_cbmaxcall();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:LogonServer.PROTO_CESHI)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:LogonServer.PROTO_CESHI)
  return false;
#undef DO_
}

void PROTO_CESHI::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:LogonServer.PROTO_CESHI)
  // required int64 bUserID = 1;
  if (has_buserid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->buserid(), output);
  }

  // required int32 cbPlayStatus = 2;
  if (has_cbplaystatus()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->cbplaystatus(), output);
  }

  // required int32 cbMaxCall = 3;
  if (has_cbmaxcall()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->cbmaxcall(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:LogonServer.PROTO_CESHI)
}

int PROTO_CESHI::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 bUserID = 1;
    if (has_buserid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->buserid());
    }

    // required int32 cbPlayStatus = 2;
    if (has_cbplaystatus()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->cbplaystatus());
    }

    // required int32 cbMaxCall = 3;
    if (has_cbmaxcall()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->cbmaxcall());
    }

  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PROTO_CESHI::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const PROTO_CESHI*>(&from));
}

void PROTO_CESHI::MergeFrom(const PROTO_CESHI& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_buserid()) {
      set_buserid(from.buserid());
    }
    if (from.has_cbplaystatus()) {
      set_cbplaystatus(from.cbplaystatus());
    }
    if (from.has_cbmaxcall()) {
      set_cbmaxcall(from.cbmaxcall());
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void PROTO_CESHI::CopyFrom(const PROTO_CESHI& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PROTO_CESHI::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void PROTO_CESHI::Swap(PROTO_CESHI* other) {
  if (other != this) {
    std::swap(buserid_, other->buserid_);
    std::swap(cbplaystatus_, other->cbplaystatus_);
    std::swap(cbmaxcall_, other->cbmaxcall_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.swap(other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string PROTO_CESHI::GetTypeName() const {
  return "LogonServer.PROTO_CESHI";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace LogonServer

// @@protoc_insertion_point(global_scope)
